require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe SaltTolerancesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # SaltTolerance. As you add validations to SaltTolerance, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SaltTolerancesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all salt_tolerances as @salt_tolerances" do
      salt_tolerance = SaltTolerance.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:salt_tolerances)).to eq([salt_tolerance])
    end
  end

  describe "GET #show" do
    it "assigns the requested salt_tolerance as @salt_tolerance" do
      salt_tolerance = SaltTolerance.create! valid_attributes
      get :show, {:id => salt_tolerance.to_param}, valid_session
      expect(assigns(:salt_tolerance)).to eq(salt_tolerance)
    end
  end

  describe "GET #new" do
    it "assigns a new salt_tolerance as @salt_tolerance" do
      get :new, {}, valid_session
      expect(assigns(:salt_tolerance)).to be_a_new(SaltTolerance)
    end
  end

  describe "GET #edit" do
    it "assigns the requested salt_tolerance as @salt_tolerance" do
      salt_tolerance = SaltTolerance.create! valid_attributes
      get :edit, {:id => salt_tolerance.to_param}, valid_session
      expect(assigns(:salt_tolerance)).to eq(salt_tolerance)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new SaltTolerance" do
        expect {
          post :create, {:salt_tolerance => valid_attributes}, valid_session
        }.to change(SaltTolerance, :count).by(1)
      end

      it "assigns a newly created salt_tolerance as @salt_tolerance" do
        post :create, {:salt_tolerance => valid_attributes}, valid_session
        expect(assigns(:salt_tolerance)).to be_a(SaltTolerance)
        expect(assigns(:salt_tolerance)).to be_persisted
      end

      it "redirects to the created salt_tolerance" do
        post :create, {:salt_tolerance => valid_attributes}, valid_session
        expect(response).to redirect_to(SaltTolerance.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved salt_tolerance as @salt_tolerance" do
        post :create, {:salt_tolerance => invalid_attributes}, valid_session
        expect(assigns(:salt_tolerance)).to be_a_new(SaltTolerance)
      end

      it "re-renders the 'new' template" do
        post :create, {:salt_tolerance => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested salt_tolerance" do
        salt_tolerance = SaltTolerance.create! valid_attributes
        put :update, {:id => salt_tolerance.to_param, :salt_tolerance => new_attributes}, valid_session
        salt_tolerance.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested salt_tolerance as @salt_tolerance" do
        salt_tolerance = SaltTolerance.create! valid_attributes
        put :update, {:id => salt_tolerance.to_param, :salt_tolerance => valid_attributes}, valid_session
        expect(assigns(:salt_tolerance)).to eq(salt_tolerance)
      end

      it "redirects to the salt_tolerance" do
        salt_tolerance = SaltTolerance.create! valid_attributes
        put :update, {:id => salt_tolerance.to_param, :salt_tolerance => valid_attributes}, valid_session
        expect(response).to redirect_to(salt_tolerance)
      end
    end

    context "with invalid params" do
      it "assigns the salt_tolerance as @salt_tolerance" do
        salt_tolerance = SaltTolerance.create! valid_attributes
        put :update, {:id => salt_tolerance.to_param, :salt_tolerance => invalid_attributes}, valid_session
        expect(assigns(:salt_tolerance)).to eq(salt_tolerance)
      end

      it "re-renders the 'edit' template" do
        salt_tolerance = SaltTolerance.create! valid_attributes
        put :update, {:id => salt_tolerance.to_param, :salt_tolerance => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested salt_tolerance" do
      salt_tolerance = SaltTolerance.create! valid_attributes
      expect {
        delete :destroy, {:id => salt_tolerance.to_param}, valid_session
      }.to change(SaltTolerance, :count).by(-1)
    end

    it "redirects to the salt_tolerances list" do
      salt_tolerance = SaltTolerance.create! valid_attributes
      delete :destroy, {:id => salt_tolerance.to_param}, valid_session
      expect(response).to redirect_to(salt_tolerances_url)
    end
  end

end
